export const environment = {
  production: true,
  remoteConfig: true,
  remoteConfigUrl: 'assets/config/dashboard-config-prod.json',
  api_token: 'f05914ea33124ba7a6cab301627c8adf',
  api: {
    auth: '/api/authentication/v1/login',
    refreshAuth: '/api/authentication/v1/refresh',
    task: '/api/task/v1/move',
    taskHold: '/api/task/v1/hold',
    taskRelease: '/api/task/v1/release',
    taskStatus: '/api/task/v1/status',
    followMe: '/api/mode/v1/followMe',
    navigation: '/api/mode/v1/navigation',
    mode: '/api/mode/v1',
    map: '/api/map/v1',
    activeMap: '/api/map/v1/activeMap',
    changeMap: '/api/map/v1/change',
    waypoint: '/api/waypoint/v1',
    pause: '/api/baseControl/v1/pause',
    resume: '/api/baseControl/v1/resume',
    localization: '/api/localization/v1',
    initialPose: '/api/localization/v1/initialPose',
    localizationPose: '/api/localization/v1/pose',
    docking: '/api/docking/v1/charging',
    mapImage: (map: string) => `/api/map/v1/${map}/image`,
    mapMetaData: (map: string) => `/api/map/v1/${map}/mapMetadata`,
    lidar: '/api/lidar/v1',
    pairing: '/api/followMe/v1/pairing',
  },
};
